/** Quick reactions shown on hover, in Slack's order of popularity. */
export const QUICK_REACTIONS = ["👍", "❤️", "😂", "🙌", "👀", "✅"] as const;

export interface EmojiEntry {
  char: string;
  name: string;
  keywords: string;
}

/** A compact, searchable emoji set for the picker (no external data files). */
export const EMOJI: EmojiEntry[] = [
  { char: "😀", name: "grinning", keywords: "smile happy" },
  { char: "😃", name: "smiley", keywords: "smile happy" },
  { char: "😄", name: "smile", keywords: "happy laugh" },
  { char: "😁", name: "grin", keywords: "smile" },
  { char: "😆", name: "laughing", keywords: "haha lol" },
  { char: "😅", name: "sweat smile", keywords: "phew nervous" },
  { char: "🤣", name: "rofl", keywords: "laugh lol" },
  { char: "😂", name: "joy", keywords: "laugh cry lol" },
  { char: "🙂", name: "slightly smiling", keywords: "smile" },
  { char: "😉", name: "wink", keywords: "flirt" },
  { char: "😊", name: "blush", keywords: "smile happy" },
  { char: "😇", name: "innocent", keywords: "angel halo" },
  { char: "🥰", name: "smiling hearts", keywords: "love" },
  { char: "😍", name: "heart eyes", keywords: "love" },
  { char: "🤩", name: "star struck", keywords: "wow" },
  { char: "😘", name: "kissing heart", keywords: "kiss love" },
  { char: "😋", name: "yum", keywords: "tasty food" },
  { char: "😛", name: "tongue", keywords: "silly" },
  { char: "🤪", name: "zany", keywords: "crazy silly" },
  { char: "🤗", name: "hugging", keywords: "hug" },
  { char: "🤔", name: "thinking", keywords: "hmm wonder" },
  { char: "🤫", name: "shushing", keywords: "quiet secret" },
  { char: "😐", name: "neutral", keywords: "meh" },
  { char: "😑", name: "expressionless", keywords: "blank" },
  { char: "🙄", name: "eye roll", keywords: "whatever" },
  { char: "😬", name: "grimacing", keywords: "awkward" },
  { char: "😴", name: "sleeping", keywords: "zzz tired" },
  { char: "😷", name: "mask", keywords: "sick ill" },
  { char: "🤒", name: "thermometer", keywords: "sick ill" },
  { char: "🥴", name: "woozy", keywords: "dizzy" },
  { char: "😎", name: "sunglasses", keywords: "cool" },
  { char: "🥳", name: "partying", keywords: "party celebrate" },
  { char: "😕", name: "confused", keywords: "hmm" },
  { char: "😟", name: "worried", keywords: "concern" },
  { char: "😮", name: "open mouth", keywords: "wow surprised" },
  { char: "😲", name: "astonished", keywords: "shock" },
  { char: "😢", name: "cry", keywords: "sad tear" },
  { char: "😭", name: "sob", keywords: "cry sad" },
  { char: "😱", name: "scream", keywords: "fear shock" },
  { char: "😤", name: "triumph", keywords: "angry huff" },
  { char: "😡", name: "rage", keywords: "angry mad" },
  { char: "🤯", name: "exploding head", keywords: "mind blown" },
  { char: "🙏", name: "pray", keywords: "please thanks thank you" },
  { char: "👍", name: "thumbs up", keywords: "yes ok good +1 like" },
  { char: "👎", name: "thumbs down", keywords: "no bad -1" },
  { char: "👏", name: "clap", keywords: "applause well done" },
  { char: "🙌", name: "raised hands", keywords: "hooray celebrate" },
  { char: "👋", name: "wave", keywords: "hello hi bye" },
  { char: "🤝", name: "handshake", keywords: "deal agree" },
  { char: "💪", name: "muscle", keywords: "strong flex" },
  { char: "🤞", name: "crossed fingers", keywords: "luck hope" },
  { char: "✌️", name: "victory", keywords: "peace" },
  { char: "👌", name: "ok hand", keywords: "okay perfect" },
  { char: "👀", name: "eyes", keywords: "look watching" },
  { char: "🧠", name: "brain", keywords: "smart think" },
  { char: "❤️", name: "red heart", keywords: "love" },
  { char: "🧡", name: "orange heart", keywords: "love" },
  { char: "💛", name: "yellow heart", keywords: "love" },
  { char: "💚", name: "green heart", keywords: "love stayful" },
  { char: "💙", name: "blue heart", keywords: "love" },
  { char: "💜", name: "purple heart", keywords: "love" },
  { char: "💔", name: "broken heart", keywords: "sad" },
  { char: "💯", name: "hundred", keywords: "100 perfect" },
  { char: "🔥", name: "fire", keywords: "hot lit" },
  { char: "✨", name: "sparkles", keywords: "shiny new" },
  { char: "⭐", name: "star", keywords: "favourite" },
  { char: "🎉", name: "tada", keywords: "party celebrate congrats" },
  { char: "🎊", name: "confetti", keywords: "party" },
  { char: "🎂", name: "birthday cake", keywords: "cake" },
  { char: "☕", name: "coffee", keywords: "tea drink" },
  { char: "🍺", name: "beer", keywords: "drink cheers" },
  { char: "🥂", name: "clinking glasses", keywords: "cheers celebrate" },
  { char: "🏠", name: "house", keywords: "home property" },
  { char: "🏡", name: "house with garden", keywords: "home property" },
  { char: "🔑", name: "key", keywords: "keys check in" },
  { char: "🛏️", name: "bed", keywords: "bedroom sleep" },
  { char: "🧹", name: "broom", keywords: "clean cleaning" },
  { char: "🧽", name: "sponge", keywords: "clean" },
  { char: "🛠️", name: "tools", keywords: "maintenance repair fix" },
  { char: "🔧", name: "wrench", keywords: "repair fix" },
  { char: "🚿", name: "shower", keywords: "bathroom" },
  { char: "🧺", name: "basket", keywords: "laundry linen" },
  { char: "📦", name: "package", keywords: "parcel delivery" },
  { char: "📅", name: "calendar", keywords: "date booking" },
  { char: "📸", name: "camera", keywords: "photo picture" },
  { char: "📎", name: "paperclip", keywords: "attach file" },
  { char: "📝", name: "memo", keywords: "note write" },
  { char: "📞", name: "telephone", keywords: "call phone" },
  { char: "💬", name: "speech balloon", keywords: "message chat" },
  { char: "✅", name: "check mark", keywords: "done yes tick complete" },
  { char: "❌", name: "cross mark", keywords: "no wrong" },
  { char: "❓", name: "question", keywords: "help" },
  { char: "❗", name: "exclamation", keywords: "important" },
  { char: "⚠️", name: "warning", keywords: "caution alert" },
  { char: "🚨", name: "rotating light", keywords: "urgent alarm" },
  { char: "⏰", name: "alarm clock", keywords: "time reminder" },
  { char: "💷", name: "pound", keywords: "money payment" },
  { char: "💰", name: "money bag", keywords: "cash payment" },
  { char: "🚗", name: "car", keywords: "drive travel" },
  { char: "✈️", name: "airplane", keywords: "travel flight guest" },
  { char: "🧳", name: "luggage", keywords: "travel guest suitcase" },
  { char: "☀️", name: "sun", keywords: "sunny weather" },
  { char: "🌧️", name: "rain", keywords: "weather" },
  { char: "🐶", name: "dog", keywords: "pet" },
  { char: "🐱", name: "cat", keywords: "pet" },
  { char: "🚀", name: "rocket", keywords: "launch ship fast" },
  { char: "👏🏽", name: "clap medium", keywords: "applause" },
];

export function searchEmoji(query: string): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return EMOJI;
  return EMOJI.filter((e) => e.name.includes(q) || e.keywords.includes(q));
}
